# Default values for prometheus.
target: example-api

statefulset:
  containerPorts: [ containerPort: 9090 ]
  initContainers:
  - name: init
    image: alpine:3.14
    command: [ chown, nobody, /prometheus ]
    volumeMounts:
    - name: data
      mountPath: /prometheus
volumeMounts:
- mountPath: /etc/prometheus/prometheus.yml
  name: config
  subPath: prometheus.yml
- mountPath: /prometheus
  name: data
volumes:
- name: config
  configMap:
    name: apicrud-backend-prometheus
volumeClaimTemplates:
- metadata:
    name: data
  spec:
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 500Mi

image:
  repository: prom/prometheus
  pullPolicy: IfNotPresent
  # tag: default

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  enabled: false
service:
  clusterIP: None
  ports: [ port: 9090 ]
  type: ClusterIP
autoscaling:
  enabled: false
