apiVersion: v2
name: example-worker
description: Example events - worker
home: https://github.com/instantlinux/apicrud
sources:
- https://github.com/instantlinux/apicrud
type: application
version: 0.1.0
appVersion: "0.1.6"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
- name: worker
  version: 0.1.1
  repository: file://subcharts/worker
- name: worker
  alias: media-worker
  version: 0.1.0
  repository: file://subcharts/worker
  condition: media.enabled
