---
# Config settings for apicrud.ServiceConfig
service_name: main
# TODO remove temp
ldap_params:
  authentication: SIMPLE
  domain: ether
  scheme: ldaps
  search_base: CN=Users,DC=ether,DC=ci,DC=net
  servers: [dc05]
