---
# Config settings for apicrud.ServiceConfig
service_name: main
ldap_params:
  authentication: SIMPLE
  # bind_dn: ETHER\svc_ldap
  domain: ether
  scheme: ldaps
  search_base: CN=Users,DC=ether,DC=ci,DC=net
  servers: [dc05]
login_ldap: true
