"""i18n_textstrings.py

Default text strings for message notifications and screen prompts
These are jinja2 templates

Supports these variable names:
  appname
  contact_id
  event_id
  guest_id
  hosts
  info
  magic
  message
  name
  sender
  siteurl
  starts_formatted
  subject

created 22-apr-2019 by richb@instantlinux.net
"""


HOST_MESSAGE = 'host_message'
TPL_HOST_MESSAGE = dict(
    subject="%(subject)s",
    html="""
<html>
List: {{ list }}<br>
<p>
{{ message }}
</html>""",
    email=u"""Hi {{ name }}! This message is from your list manager:

List: {{ list }}

{{ message }}
""",
    sms="""Host message from {{ appname }}: {{ message }}"""
)

PASSWORD_RESET = 'password_reset'
TPL_PASSWORD_RESET = dict(
    subject="""Welcome and please confirm your %(type)s""",
    html="""
<html>
Welcome to Example service! Your contact info {{ info }} was added to {{
 siteurl }} by {{
 sender }}. The next step is to set a password. Click to confirm this is you:
<table width="100%" cellspacing="0" cellpadding="0">
  <tr><td><table cellspacing="0" cellpadding="0">
    <tr><td style="border-radius: 2px;" bgcolor="#43BBC1">
        <a href="{{ siteurl }}/#/confirm?token={{ token }}"
        target="_blank" style="padding: 8px 12px; border: 1px solid
        #43BBC1;border-radius: 2px;font-family: Helvetica, Arial,
        sans-serif;font-size: 14px; color: #ffffff;text-decoration:
        none;font-weight:bold;display: inline-block;">
        Set your password</a>
    </td></tr>
  </table></td></tr>
</table>
Ignore this message if you don't wish to receive further correspondence.
</html>""",
    email=u"""Your contact info {{ info }} was added to {{ siteurl }} by
{{ sender }}. The next step is to set a password, go to
{{ siteurl }}/#/confirm?token={{ token }}.

Ignore this message if you don't wish to receive further correspondence.
""",
    sms="""See {{ siteurl }}/#/confirm?token={{ token }} to confirm request by {{
 sender }}"""
)

CONTACT_ADDED_REQUEST = 'contact_add'
TPL_CONTACT_ADDED_REQUEST = dict(
    subject="""Please confirm your %(type)s""",
    html="""
<html>
Your contact info {{ info }} was added to {{ siteurl }} by {{
 sender }}. Click to confirm this is you:
<table width="100%" cellspacing="0" cellpadding="0">
  <tr><td><table cellspacing="0" cellpadding="0">
    <tr><td style="border-radius: 2px;" bgcolor="#43BBC1">
        <a href="{{ siteurl }}/#/confirm?token={{ token }}"
        target="_blank" style="padding: 8px 12px; border: 1px solid
        #43BBC1;border-radius: 2px;font-family: Helvetica, Arial,
        sans-serif;font-size: 14px; color: #ffffff;text-decoration:
        none;font-weight:bold;display: inline-block;">
        Confirm contact info</a>
    </td></tr>
  </table></td></tr>
</table>
Ignore this message if you don't wish to receive further correspondence.
</html>""",
    email=u"""Your contact info {{ info }} was added to {{ siteurl }} by
{{ sender }}. To confirm this is you, go to
{{ siteurl }}/#/confirm?token={{ token }}.

Ignore this message if you don't wish to receive further correspondence.
""",
    sms="""See {{ siteurl }}/#/confirm?token={{ token }} to confirm request by {{
 sender }}"""
)

FOOTER = 'footer'
TPL_FOOTER = dict(
    html="""
This message was generated by {{ appname }} hosted at {{ siteurl }}, a
an example of the apicrud service.
You can adjust your communication preferences by visiting this link:
<p>
<table width="100%" cellspacing="0" cellpadding="0">
  <tr><td><table cellspacing="0" cellpadding="0">
    <tr><td style="border-radius: 2px;" bgcolor="#43BBC1">
        <a href="{{ siteurl }}/#/prefs?guest_id={{ guest_id }}&magic={{
                 magic }}&cid={{ contact_id }}"
        target="_blank" style="padding: 8px 12px; border: 1px solid
        #43BBC1;border-radius: 2px;font-family: Helvetica, Arial,
        sans-serif;font-size: 14px; color: #ffffff;text-decoration:
        none;font-weight:bold;display: inline-block;">
        Messaging Preferences</a>
    </td></tr>
  </table></td></tr>
</table>
<br>
Software copyright &copy; 2020 Richard Braun &bull; San Francisco, CA<hr>
""",
    email=u"""
---
This message was generated by {{ appname }} hosted at {{ siteurl }},
an example of the apicrud service.
You can adjust your communication preferences by
visiting this link:
{{ siteurl }}/#/prefs?guest_id={{ guest_id }}&magic={{ magic }}&cid={{
   contact_id }}.

Software copyright (C) 2020 Richard Braun * San Francisco, CA
""",
    sms=""
)

# TODO this is a bit of an ugly hack to pass these templates by
# reference for serialization to celery--maybe there is a pythonic
# way to do this
TPL = {
    CONTACT_ADDED_REQUEST: TPL_CONTACT_ADDED_REQUEST,
    FOOTER: TPL_FOOTER,
    HOST_MESSAGE: TPL_HOST_MESSAGE,
    PASSWORD_RESET: TPL_PASSWORD_RESET,
}
