# Local dev - you need 6 services running. This assumes you have
# kubernetes available to run the 3 adhoc services listed below.
#
# To iterate on UI/API/worker code, clone github.com/instantlinux/apicrud-ui
# into another directory, start 3 shell sessions and invoke the following to
# launch the following commands in separate sesions:
#    make run_local       # (from top level of this clone)
#    make messaging_worker
#    make ui_local        # (from the other clone)

run_local: py_requirements envsubst redis_adhoc mariadb_adhoc
	. $(VDIR)/bin/activate && APP_ENV=$(APP_ENV) \
	  AMQ_HOST=$(RABBITMQ_IP) REDIS_HOST=$(REDIS_IP) \
	  PUBLIC_URL=http://$(FQDN):$(APP_PORT) \
	  FLASK_ENV=development PYTHONPATH=example python3 -m example.main

messaging_worker: rmq_adhoc
	. $(VDIR)/bin/activate && cd example && \
	  AMQ_HOST=$(RABBITMQ_IP) PYTHONPATH=.. \
	  celery -A messaging worker -Q messaging_$(APP_ENV) \
	  -n messaging1@%h --loglevel=INFO

ifeq ($(shell uname -s),Darwin)
envsubst: /usr/local/bin/envsubst
else
envsubst: /usr/bin/envsubst
endif

/usr/local/bin/envsubst:
	HOMEBREW_NO_AUTO_UPDATE=1 brew install gettext
	brew link --force gettext

mariadb_adhoc:
	SERVICE_IP=$(MARIADB_IP) make example/k8s/mariadb

redis_adhoc:
	SERVICE_IP=$(REDIS_IP) make example/k8s/redis

rmq_adhoc:
	SERVICE_IP=$(RABBITMQ_IP) make example/k8s/rmq
