apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local.fullname" . }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      # scrape_interval:     60s  # Default is every 1 minute.
      # evaluation_interval: 60s  # The default is every 1 minute.
      # scrape_timeout:      10s  # The default is 10 seconds.
    scrape_configs:
    - job_name: {{ include "local.fullname" . }}
      metrics_path: /api/v1/metrics
      static_configs:
      - targets: ['{{ .Values.target }}:8080']
    - job_name: prometheus
      static_configs:
      - targets: ['localhost:9090']
