apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "local.fullname" . }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "local.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "local.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "local.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: data
          mountPath: /prometheus
      initContainers:
      - name: {{ .Chart.Name }}-init
        image: alpine:3.14
        command: [ chown, nobody, /prometheus ]
        volumeMounts:
        - name: data
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: {{ include "local.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 500Mi
