apiVersion: v2
name: apicrud-backend
description: Backend services and monitoring
home: git@github.com/instantlinux/apicrud.git
sources:
- git@github.com/instantlinux/apicrud.git
type: application
version: 0.1.0
appVersion: "0.1.6"
dependencies:
- name: chartlib
  version: 0.1.7
  repository: https://instantlinux.github.io/docker-tools
- name: mariadb
  version: 0.1.0
  repository: file://subcharts/mariadb
  condition: mariadb.enabled
- name: prometheus
  version: 0.1.0
  repository: file://subcharts/prometheus
  condition: prometheus.enabled
- name: redis
  version: 0.1.0
  repository: file://subcharts/redis
- name: rmq
  version: 0.1.0
  repository: file://subcharts/rmq
