apiVersion: ENC[AES256_GCM,data:pUE=,iv:xlSwiBg4izNw6OSyPTMFGfqHYgYW2UfCXWEK2+ipYm4=,tag:cBWxRWNHzw7Zp+oYglmR7g==,type:str]
data:
    example-redis-aes-secret: ENC[AES256_GCM,data:sh+ThZTIN9at2n1DGe2FOanlKi+OoakO,iv:mJeJAFowSRUDfTrNxu1qxYwtEZSyqTwHu6dxrf9Qbig=,tag:WH++CVfvwaKFLyvhz9Lg5g==,type:str]
kind: ENC[AES256_GCM,data:CLoiAJba,iv:AUf8oMrLQyl23tnh2VGCB+KMvqLYUxKhWRhX+BgIsWs=,tag:gNyeaGd2PT+9g6BWisSF3g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SEFqtIY8CBmWL0xajnBVqq532uQlY3es,iv:H7iFQfCAQ+y/ACp7omWT9PHfbE1kc3u1rkRkzjdeZCM=,tag:ISiCg1y9ZrgfsuT6Fy6k9w==,type:str]
type: ENC[AES256_GCM,data:i2PPQgqH,iv:EbQDCC28XrEi5YwTbxGn3YgQ76BJ1bj/Vak5Xn94Q30=,tag:KbQ/2OrTqe/nSRz3co7xNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-04-20T15:12:55Z'
    mac: ENC[AES256_GCM,data:OmSwuAQMgzD+DRgRCMqxn3Rnbn1YyaJsGIinB28wevUNiztRHL7AC1BIm9fq19rPSFcOnDK8N/VLCoIOZHepA931u3S8t8XX0x2cx4YMSgtwUVWo3SfXnSfaiTSqHXkyvTSBE31Befr226zGvCtuYtik0emkRXPha8M5wBxH/48=,iv:HRbBO/TeWjHZQjJI/Z/52MJQBjPhEs6vrzX605iyLGI=,tag:AZ5P2gLLFhPfkFvEgV2bdA==,type:str]
    pgp:
    -   created_at: '2020-04-20T06:22:39Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2NfUSia5heKAQv/WsJOlgLwSRKoO6b5CXg09qnxoyhpkAaK+0hSxrtNGK0Q
            hdNhrZYDRbM9d4ZEDLwUO/QELIo+dTtv+H1iseoZNYJ2e4yCHfKnvVlA20Q6l6Xc
            gjAPrtApKr2gNjkvob66zQgN9daN+d9+rgEdWR5oIePC0lqVv4kGlvC06w0+Egbf
            VXBQ7+MwX8M3WAPKjV09tmzr8yFnN2ln9abI0eERQY+Z+/rNlgJsca5AbavO/0OI
            I+3gNyQDIdxhpCEzERDwSPvMipGMH1p2v8R+t0apbIVoYMDfFx7wLZaj+RfMjDem
            DR8j4xv15ksBVhLaqPmclVcgDuKl4+2ZWoFpXNMohZPzZJLDpdhkOoJQFR9YQIr0
            s1NKbhtQkMpFYpIZXoPj0yNRFgrMBRKfy95fqfWhDgHpfjE0OZhwaSKQKGe5M8hf
            vTU4Oc2thGR57TBNTw2Wb0Zs+LwiX2/uUEIduMr0SVk/NBX3+n+wGnRDyToI2t7X
            omlSDDFP81UgK5uHjev80lwBitsKbP7YnFw2mL6z+DWqurIMLo1EF4reUmCT1QSk
            PJO5EUDxJGR92pZOpKjxiQz+36X75ZwW2v/paNeTeBCVIlFoxss7pgMf791kqhBt
            qbxG5F2A3ZmCzDSBCw==
            =vEAz
            -----END PGP MESSAGE-----
        fp: B2641794AFE7323506B6DEDA38E3A229A778E291
    unencrypted_suffix: _unencrypted
    version: 3.5.0
