apiVersion: ENC[AES256_GCM,data:fBk=,iv:z0QLKsTAHCliZ0fMNinLNc3SkCziwPjTtAmL0dkyEL0=,tag:AvkB7AakXr9l3Un4K7pu+Q==,type:str]
data:
    example-db-aes-secret: ENC[AES256_GCM,data:fFGJEL917isNocr7/Ci1tQ78hHnln458,iv:tGQrVjaTv+PCMU/4aXMkm4l8D577pG/XJhsfqIk+t2g=,tag:PQxL8g7gxJ/XwBmnQ5oPZQ==,type:str]
kind: ENC[AES256_GCM,data:rhol/MB7,iv:bJe/3FhTU+uT06AyMCUsekfTmdknp1RTOiKhTk5QcDg=,tag:e3kDK9lV8kw/lwCT2b8kPw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HL0t9ygucBhflyv6OuKEafuog2ga,iv:cocPXZtbjqZSFGvA+ZYpuWiDsrDwsrjPNo5WYf5pl8U=,tag:XUyY4Hqv0+8Xp6qrdhEpfg==,type:str]
type: ENC[AES256_GCM,data:+Zq6qAPI,iv:Cfq01zg2e1+bvTV5KG0ZuHtNaSk+d+SpFz3W2tVlm9M=,tag:sk6qd7opGiDkp8Myzgpt1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-01T15:07:22Z'
    mac: ENC[AES256_GCM,data:91vf2Age3lvWJk382RDiY2yK42YNGx0/w6ZlAtXjNihDiNNEK9dCP2nTC3hhfdT5XUMr6Z6AJQN6w6fyni5rjsA9BuhUf+/TPMpA0WIfbV6fu09zLWGavt61IlKxV0tnmUtsvI4srWtpramWNiuoM4/k7c788L2D27EY4Ap7URs=,iv:E6pG78D0p+TECARcPQDEeR7yB6W1Y3G37X5CbMNO+EM=,tag:rcvXTNsYO6MY7RuNSPubIw==,type:str]
    pgp:
    -   created_at: '2020-05-01T15:06:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2NfUSia5heKAQv/W6kNjoT/dI7yzg+NoLGa8GjVCuErvPRK/gIOwMaGPKR6
            w9tvS0dU7RqYIiTuHYFu9h/nI2E30iOvudN6/gfJQvHU/nY59UtXUuuJMJyx+8Fb
            9PDEra9uIf42nT4+MajEVJpq5Ust6JYiSS+bXpwMMg6GA03e47AZAIv24cVjhSyQ
            xxrFWQT2VXhWlLJz3QBDJz4YotQHLz7vk0YhmxKn0NVlonpXF8KCA/f1gX8VxJmV
            eX0p046hI5L+Qi0I0dE1CGL8U+8X6b4N/ZdxUJYuM6JU0TtyE2VvkKh9cO9x3cKq
            dhboivoHxjdd8M7dxWI/ONN2M/FFjNbBwu6zu/qU4FrjFD0owIX2sFmgEjedVQ96
            nlcml2cCqcsrLpDZqPuFE6RAQO18cMrSc6H6cjBkLc0g65lx2fL1AqvLzRt4g10d
            vyFeiaS679GT5gTvJ/OYUwq+uaFsVMq4ZFpq6PNC7yfaTYHbpNc9kc1frZnyEL1k
            wHBDRHm7q70rdQyoGzV+0lwBYIwlG8AhS8wolJmJrkQDs57fKpFDjR7VBhaysF1u
            AycZ+59SuQYnEhh4f6kZHdU6OmzoHqBOzVCoElCLQmDl7adRUbND6upGkVukmGK+
            7vuG5xanc2Q7BWB0pg==
            =3HVh
            -----END PGP MESSAGE-----
        fp: B2641794AFE7323506B6DEDA38E3A229A778E291
    unencrypted_suffix: _unencrypted
    version: 3.5.0
