apiVersion: ENC[AES256_GCM,data:Gx4=,iv:daTdFWZ9OJUCUZ6FOFqJu5b+8fsVdm4hE01iXEa2+L4=,tag:4TpLqFtGion4xTLkAyG76w==,type:str]
data:
    mariadb-root-password: ENC[AES256_GCM,data:FWhbzhjEWZaveLAD2aSkDwdKnG+03WAb,iv:BQ1/HHk7JQydByQ3H1w5pzlj6CzA1HuHYbq/cApBVgs=,tag:ggKZYnFr1d0rCVDFPI6i6g==,type:str]
kind: ENC[AES256_GCM,data:Ad6CtBc4,iv:6jCWJvUlWpud9bl4oxEEZAJpAX+i3GE3fX/GSCrHye8=,tag:H/FptgvBDp4sHcJMtyxc7Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e90NG/8mVqizza/uT6PrB9DuNMB0,iv:iybimK5eti3eAN34r3Ee4CxtG5lAk3ML6mPQ0yZ7rxg=,tag:wc9yM79rQh9EsMy/kNoFSQ==,type:str]
type: ENC[AES256_GCM,data:xaVpjAzK,iv:AeUCmWk38E2HtouQED9IQlnhFHTKem4e9QT5z6R2BEo=,tag:1+kNuLRTZHJgdNtKhl4SCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-05-04T05:22:43Z'
    mac: ENC[AES256_GCM,data:lpLytnY+w3xm7cZddpqDZr7c52xbtOaThZIGQsXQvxgUCE6mD27MEZJvdDhya4RwHfKA0yGGzPjfnQTeYnv/r90hyFmbxknv+AJu+7soGl7zRGVu3oXrsl+q3SAihd+BWNbVbUQjzoK2BaWnKAVaMmJ+Iy/kjTRBhgu02Vix5u8=,iv:0YF7N0DixwscTXBVdBjuBXsGq3HRkmQ6qxDOB7w+OcU=,tag:0UPEKFCebaGuOQCZci0JaA==,type:str]
    pgp:
    -   created_at: '2020-05-04T05:18:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA2NfUSia5heKAQv/WP5GmFTqFKGc7irD8/pNLlsHttoO3RNmPV6xG0QUpcUx
            bnF9u6Vy/+aop8MaS5zYvzIwjAaSbTYbSDQQLDKmTOU7n4DJB5WN57sYkx2wlnU6
            uxSdZhrY9Uvhu3JJk87CWU+68zTcBtvsr/ERzw2qxDGbenZtXuCpFBHT8yyfICV6
            JLWAxEUNJnEbEeshCsKacqJU0smh9RFxX4RqGglQGuzd2WlElkmJR+AVTDiexLv9
            Lj0ogOG/elG6sMEWf2ZcXYt1xx1lqvRg7z2W5FBC/cD/rEmXs+nSen/u72FLuAKY
            6OJVTO3Cu6EVtM7+DEGXnA41UKycXjlQtgKWNWY5sq/LsxnTcrYmsJ5lY4ZV3bE/
            4+jhZ1OzUOwYnRZNk3DWbiTM7DGI3w8RtDcZA83U+ifw+fB53TnZW3ueDgafR0Ru
            dzhfjQ74VrdMa8ANcLpm/w1gwInNQOwy1qiwToqDw90wgEKMst0whFkxeiB6KzG2
            5E6P+/s9hZZHQnb8XZCn0l4Bn4oJu7P66ukrtpvunnXqvDm1oKo6kKtuYBBlr2ay
            F8wkuCd2zsFiYQSGxaUgjaf2mmRyXQV+gDOt6GtckdSn0TWenDVozBTiYWIyNfi/
            oDGLQ534ND5zewT72zw6
            =LTmn
            -----END PGP MESSAGE-----
        fp: B2641794AFE7323506B6DEDA38E3A229A778E291
    unencrypted_suffix: _unencrypted
    version: 3.5.0
