apiVersion: v2
name: example-ui
description: Example events - UI
home: https://github.com/instantlinux/docker-tools
sources:
- git@git.instantlinux.net:richb/example.git 
type: application
version: 0.1.0
appVersion: "0.1.6"
dependencies:
- name: chartlib
  version: 0.1.6
  repository: https://instantlinux.github.io/docker-tools
- name: ui
  version: 0.1.0
  repository: file://subcharts/ui
