---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: apicrud-media
  name: apicrud-media
spec:
  replicas: $REPLICAS_API
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apicrud-media
    spec:
      containers:
      - name: apicrud-media
        env:
        - { name: AMQ_HOST, value: $AMQ_HOST }
        - { name: APP_ENV, value: $APP_ENV }
        - { name: CORS_ORIGINS, value: "$CORS_ORIGINS" }
        - { name: DB_CONNECTION_TIMEOUT, value: "$DB_CONNECTION_TIMEOUT" }
        - { name: DB_HOST, value: $DB_HOST }
        - { name: DB_NAME, value: $DB_NAME }
        - { name: DB_USER, value: $DB_USER }
        - { name: DOMAIN, value: $DOMAIN }
        - { name: PUBLIC_URL, value: $MEDIA_URL }
        - { name: REDIS_HOST, value: $REDIS_HOST }
        - { name: TZ, value: $TZ }
        - name: DB_AES_SECRET
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-db-aes-secret
              key: $SERVICE_NAME-db-aes-secret
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-db-password-$APP_ENV
              key: $SERVICE_NAME-db-password-$APP_ENV
        - name: FLASK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-flask-secret
              key: $SERVICE_NAME-flask-secret
        - name: REDIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-redis-aes-secret
              key: $SERVICE_NAME-redis-aes-secret
        image: $REGISTRY_URI/$REGISTRY_PATH-media/apicrud-media:$TAG
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: /api/v1/health
            port: $MEDIA_API_PORT
        ports:
        - containerPort: $MEDIA_API_PORT
        resources:
          limits:
            memory: $LIMIT_MEM_API
          requests:
            cpu: $LIMIT_CPU_REQUEST
            memory: $LIMIT_MEM_REQUEST
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: apicrud-media
  name: apicrud-media
spec:
  ports:
  - { port: $MEDIA_API_PORT, targetPort: $MEDIA_API_PORT, name: media }
  selector:
    app.kubernetes.io/name: apicrud-media
