---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME-redis
spec:
  clusterIP: $SERVICE_IP
  ports:
  - port: 6379
  selector:
    app.kubernetes.io/name: $SERVICE_NAME-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME-redis
  labels:
    app.kubernetes.io/name: $SERVICE_NAME-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: $SERVICE_NAME-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME-redis
    spec:
      containers:
      - name: redis
        #   args: [--requirepass, $(REDIS_PASS)]
        #   env:
        #   - name: REDIS_PASS
        #     valueFrom:
        #       secretKeyRef:
        #         name: $SERVICE_NAME-redis-password
        #         key: $SERVICE_NAME-redis-password
        image: redis:$VERSION_REDIS-alpine
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: $SERVICE_NAME-redis
