---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME-ui
  name: $SERVICE_NAME-ui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME-ui
    spec:
      containers:
      - name: $SERVICE_NAME-ui
        env:
        - { name: REACT_APP_API_URL, value: http://$EXAMPLE_PUBLIC_URL/api/v1 }
        # - name: REACT_APP_TOKEN_MAPBOX
        #   valueFrom:
        #     secretKeyRef:
        #       name: example-token-mapbox
        #       key: example-token-mapbox
        - { name: TZ, value: $TZ }
        image: $REGISTRY_URI/$REGISTRY_PATH-ui:$TAG
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: $LIMIT_MEM_DEFAULT
          requests:
            cpu: $LIMIT_CPU_REQUEST
            memory: $LIMIT_MEM_REQUEST
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME-ui
  name: $SERVICE_NAME-ui
spec:
  clusterIP: None
  ports:
  - port: 80
  selector:
    app.kubernetes.io/name: $SERVICE_NAME-ui
