---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME-worker-$QUEUE
  name: $SERVICE_NAME-worker-$QUEUE
spec:
  replicas: $REPLICAS_WORKER
  template:
    metadata:
      labels:
        app.kubernetes.io/name: $SERVICE_NAME-worker-$QUEUE
    spec:
      containers:
      - name: $SERVICE_NAME-worker
        env:
        - { name: AMQ_HOST, value: $AMQ_HOST }
        - { name: APP_ENV, value: $APP_ENV }
        - { name: CELERY_APP, value: $CELERY_APP }
        - { name: DB_CONNECTION_TIMEOUT, value: "$DB_CONNECTION_TIMEOUT" }
        - { name: DB_HOST, value: $DB_HOST }
        - { name: DB_NAME, value: $DB_NAME }
        - { name: DB_USER, value: $DB_USER }
        - { name: QUEUE, value: $QUEUE }
        - { name: REDIS_HOST, value: $REDIS_HOST }
        - { name: TZ, value: $TZ }
        - name: DB_AES_SECRET
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-db-aes-secret
              key: $SERVICE_NAME-db-aes-secret
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-db-password-$APP_ENV
              key: $SERVICE_NAME-db-password-$APP_ENV
        - name: REDIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              name: $SERVICE_NAME-redis-aes-secret
              key: $SERVICE_NAME-redis-aes-secret
        image: $REGISTRY_URI/$REGISTRY_PATH/$SERVICE_NAME-worker:$TAG
        ports:
        - containerPort: 5555
        resources:
          limits:
            memory: $LIMIT_MEM_WORKER
          requests:
            cpu: $LIMIT_CPU_REQUEST
            memory: $LIMIT_MEM_REQUEST
      imagePullSecrets: [ $IMAGEPULL_SPEC ]
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: $SERVICE_NAME-worker-$QUEUE
  name: $SERVICE_NAME-worker-$QUEUE
spec:
  ports:
  - port: 5555
  selector:
    app.kubernetes.io/name: $SERVICE_NAME-worker-$QUEUE
