{{- if .Values.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "local.fullname" . }}-nodeport
  labels:
    {{- include "local.labels" . | nindent 4 }}
spec:
  ports:
  - { port: 80, targetPort: 80, nodePort: {{ .Values.nodePort }} }
  selector:
    {{- include "local.selectorLabels" . | nindent 4 }}
  type: NodePort
{{- end }}
