# Default values for api.
nodePort: None
deployment:
  containerPorts: [ containerPort: 8080 ]
  env:
    amq_host: example-backend-rmq
    app_env: dev
    cors_origins: https://dev.example.com
    db_connection_timeout: 1780
    db_host: db00
    db_name: example
    db_user: example
    public_url: https://dev.example.com
    redis_host: apicrud-backend-redis
    redis_port: 6379
    tz: UTC
  xenv: []
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  httpGet:
    path: /api/v1/health
    port: 8080

image:
  repository: registry.gitlab.com/instantlinux/apicrud/example-api
  pullPolicy: IfNotPresent
  # tag: default

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  enabled: false
service:
  clusterIP: None
  ports:
  - { port: 80, targetPort: 8080, name: web }
  type: ClusterIP
autoscaling:
  enabled: false
