# Default values for rmq.
statefulset:
  env:
    rabbitmq_erlang_cookie: secret
  containerPorts:
  - containerPort: 4369
  - containerPort: 5671
  - containerPort: 5672
  - containerPort: 25672
volumeMounts:
- mountPath: /var/lib/rabbitmq
  name: rmq
volumeClaimTemplates:
- metadata:
    name: rmq
  spec:
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 500Mi

image:
  repository: rabbitmq
  pullPolicy: IfNotPresent
  # tag: default

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  enabled: false
service:
  clusterIP: None
  ports:
  - { port: 4369, targetPort: 4369, name: epmd }
  - { port: 5671, targetPort: 5671, name: amqp-ssl }
  - { port: 5672, targetPort: 5672, name: amqp }
  type: ClusterIP
autoscaling:
  enabled: false
